---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meditrack-jwt-keys
  namespace: meditrack-prod
spec:
  encryptedData:
    JWT_PRIVATE_KEY_B64: AgB/rROnM8tb+s0Z2UHWT8OJFhkPmIDJiQbMJFEnCyHCw+GhROV8yKmkEiV44rLs/j7hRc/7Jjx+zuy8im+L8tZXIE6TolgYt6A9NH337DUWOxsP1LKuCcvffgT8QrprK1mOCJqTn8Pq9SNBN299MXlTdkD6ebKdXMt/yw8qjE9EKJ70/YYswfDcZgyoTXvWBzDG+S0hoL77U2a7c+bHnUsoFyO8ElEJ8VUcKIfJNMNKOc2msesb2RpV22qQlOoYYL2JJnerN772QUMZvy3JFMq5AvK/o/Mp9QdWC02DbDKM5vjUwcXzEI4eh2lNQRAGTbHVF4znoWxZVKVJWo6bIiuBsABpk68AIPoJyr4Kej+VkZwDI8RaLTz/Wveo1oyLBFtuVRQr/vlTShVSrSzR/Wq/QdMC5MRwZtkorrDXf80P0oHhzzMrRaVfLEeCh6zDCKzmz6aw8qtT+HQEshG/Q064oZxYGt4In3FJvTUC2OFORG6gPympZsk782CAgPQ65vbiC5r6AldfTCJT5ZYOAZ3YXg6EDcYTGHSw1PShD4/ov2B6mV6i2uY6/KeeNiJ4xVoE/RKNGvsAaFKDyYJzDN1Eb2Yh5x3hKMbUSFBVvlmq/220bJt2QyfjtQyGBvvhvuF2FRsNRURJJrGsaj+5qcp/Vs4x3DkGUTZD6Umf7Swt5U4MbdFnWPdxmluA0TgasVU=
    JWT_PUBLIC_KEY_B64: AgAjMLtpgwtKRTFMIOhd9wTPrvTfpT+oQGU9bxuKaKpX+8Ex8hhxWmhqpkA+/7HhTsh7+w7fG8cpP1NhCadEKj2lCZQGewY8RtVmyd4DX3UqSV0bDmSx0r9kkvh7YdFqK43fO1rRiZE8eU9kh682clJeI0t/ZDtirnJf9tUjrZMDZkfrwDa2RZ2UQadrhDzYJdz0/IRHEOy5JBy4emiHLX8FipITSqtr7bIVk69oIWR/7YIl64ovW+Cb3KzGOF0gKNcGipfcSnSDXge6/7xlV+KdnKaHKEFo9NfOjc8O50Ywgm7TA5Ntf7Fq16EmkTzMTYxu3NJ30rF2G3nR2Y04CVM266O8g4n1Q8kNzvrTNQ5npqdWpWVJJut9dVb8wSLeUUSqurUp/4UbtwkylXLU+yZEuaXRAhErInS9zv05kTQnDKtvUFEObgjnxTdtqquyWVZK5eCTqkGBPjxGHA1XVCJwXQbFPOSOFfbFTmVtoGnqK7xwCJfTN43Qqs28kqiepnITt+3Xk1TO4AwkaHmfIljJtQCKkQ1U6qPYaT6zd7CgsucHCIqY2/QBV5GwcCqfXNbIeOcAN47USkXdUXgz1uxB1OhyhjutrdQe8jdaZulcLUXz/kKNGditbpkMZIQMz4wrn8Z+ohewk8Apb+a4NqCCMBa0qZgHI5XPkpXrvFwBJPMn6mKXiaFQCya9y70mTzk=
  template:
    metadata:
      name: meditrack-jwt-keys
      namespace: meditrack-prod
