---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meditrack-jwt-keys
  namespace: meditrack-dev
spec:
  encryptedData:
    JWT_PRIVATE_KEY_B64: AgCAsdZQAxpkCUQVjo364EANcq4nY3lSFbzCjYtEHrrsOOkevdw/5QW7bXgQVbc5on+UhGeFuiJ7Hee7GM3qo4p8bDW4B2JyBTst0Hk+O/fG6eKeCyi71iuA4zjnkXSn+QAbnWZPZT7uzeurNqouLi/yxD35UlPr/NoqiRlqijIpyDxqNTgy2nlpkeeqdUVb9vtPRyeYfm3wVDttKGhHot7XhNdGv9UBZGjJ7Wm1EM5Yrb3I9z1JxQ8St+le75Vxcm1ozqm05G6b+8sKM0SaL+fCnGnGFTknmijlAyduBL24qbYrMKB9h1RLv+/GCbY0UTvnNwGCWYipqXh4tIw7tXC8ILlfmfpRmzv3KwauYBlDM5k0oaNkr4a3rp7Xz/hNbBDiCnW0uNYGRiv/FOaBlu462uibDN8wX5Gc5T6ev2J6fQAEpomO1xzA7agE6OK0FGJXmaQIK5GiK1qw3LjjooJo9FcnSC1vxD/99I8u6tS3bICg1k3rWRlK59k0ZHXFYqHb4EpeUvjHbWfhMuvvZoA5jnmJFMft0c71+gMcUACfKLxZnNTb1MOuNNkacU864o1xbVVn+Ns4vGPLL5MpshP1P6IsZaFmwp7T61p9Usi1mJzpgvCUO9XVGEwzH8HoC+LIGHwXEto3GrUD2zJcLsoz7Dpx+o5JgNdpQH47HAF8FJ6YyOcFOPrhxTThFcGEIbc=
    JWT_PUBLIC_KEY_B64: AgBB4M8FIm5YdJ+eKYM9irfz1oxqUx3IDQ6T6uB8m+/QcsWDB3RMRWv35rRF8sfCeu2X9rc4UT63S35wLTGY5p52eauiqSK8SdUd+hxL86D1tw0J77oMh9PeZaNqrixMa+Sju0urQiXV5/3xf17k4D1PKwM2PtsxYmn2QjOuFDJGwFweaCXrr29fnoiinEeu0pAyc4hxRTlOR9xja3QD3avftkzR40cRa10hCq3eSCg8/iirfu4tCk+H6Uma+KhbZafZkip/8Ztkln2kWj3RPsg+r5VxxgbApFpOYcn/fNUnq/GJvpeF7pK/QNt9pPs9toPyzGPJFL9+i7eyoMj+ZSWa/N4hgeAj0KMzS7hQ4vxZ7EJdZf+tO6SuJmoy8+Un9I5a5TG8Eg/YbPmMo27a7SPrmKKw0l1+/EDU2awB2QqPRTm39VYz80VytvRnJpTB9PGuhBgceBrIIlr1h2eU49kfMnJsSIItpx9G6lE3mi1utocW8ZWsG6Ubn5i/9NKUs41fecBkJdQInwRue3jtlyNi6rDKMi2J5kAOm37bALjQleAAHRLuEJCoXckdHo0R7SsJoqaGF6atMCTKZlfZHzBFK4ax8BVoQkO4//3C1CTWEfn6uqDpulC+fqYcMFBnfLhx3ft8gQBDuB9cXQqJuGaTQt+pDR+0X+feOHIWm4nuggfdZHUrjTN/P0vc7Bz9g/I=
  template:
    metadata:
      name: meditrack-jwt-keys
      namespace: meditrack-dev
