apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.global.nfs.storageClass }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
provisioner: cluster.local/nfs-provisioner
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  archiveOnDelete: "true"
mountOptions:
  - nfsvers=4.1
  - hard
  - nointr
