apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aiService.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ai-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.aiService.name }}
  ports:
    - port: {{ .Values.aiService.port }}
      targetPort: {{ .Values.aiService.port }}
      protocol: TCP
