{{- if .Values.redis.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.redis.name }}-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.redis.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
{{- end }}
