apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.healthDb.name }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "health-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ .Values.healthDb.name }}
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.healthDb.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "health-db.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.healthDb.name }}
  ports:
    - port: 5432
      targetPort: 5432
