apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.prod }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace.prod }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.dev }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace.dev }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.infra }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace.infra }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace.monitoring }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace.monitoring }}
