# ─────────────────────────────────────────────────────────────
# MediTrack — Namespace definitions for all environments
# Environment: cluster-scoped
# Namespace: N/A (creates namespaces)
# Phase: 2 — Kubernetes + Helm Implementation
# ─────────────────────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.prod }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.namespace.prod }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.dev }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.namespace.dev }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.infra }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.namespace.infra }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.monitoring }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
    name: {{ .Values.namespace.monitoring }}
