{{- if .Values.global.haproxy.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: haproxy-pdb
  namespace: {{ .Values.global.namespace.infra }}
spec:
  minAvailable: {{ .Values.global.haproxy.pdb.minAvailable }}
  selector:
    matchLabels:
      app: haproxy
{{- end }}
