apiVersion: v1
kind: Service
metadata:
  name: meditrack-gateway-nodeport
  namespace: {{ .Values.global.namespace.infra }}
  labels:
    app: haproxy
    app.kubernetes.io/name: haproxy
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
    - name: http-prod
      port: 80
      targetPort: 80
      nodePort: {{ .Values.global.haproxy.nodePorts.prod }}
    - name: http-dev
      port: 81
      targetPort: 80
      nodePort: {{ .Values.global.haproxy.nodePorts.dev }}
    - name: stats
      port: 8404
      targetPort: 8404
      nodePort: {{ .Values.global.haproxy.nodePorts.stats }}
