{{- if .Values.global.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: meditrack-gateway
  namespace: {{ .Values.global.namespace.infra }}
  labels:
    {{- include "meditrack.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.global.gateway.className }}
  listeners:
    - name: prod
      port: 80
      protocol: HTTP
      hostname: {{ .Values.global.haproxy.hosts.prod }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespace.prod }}
    - name: dev
      port: 80
      protocol: HTTP
      hostname: {{ .Values.global.haproxy.hosts.dev }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.global.namespace.dev }}
{{- end }}
